### PR TITLE
DDL and DML commands

### PR DESCRIPTION
**Pull request by PiyushNegi1703**
Added the SQL file for DDL and DML commands for milestone 2.

### CODE REVIEW

**Comment by PiyushNegi1703** [comment]
Loom video - https://www.loom.com/share/82781fe51dc64a0c81c3e9aeacdd720b?sid=15272e30-869c-4f17-94e7-8066124e8678

**Review by th3c0d3br34ker — COMMENTED** [review]
thanks @PiyushNegi1703 for your submission. the self-viva covers `DDL` and `DML` commands well. 

suggestion: 
consider explaining all the available `DDL` and `DML` commands.

thanks

**Comment by PiyushNegi1703** [comment]
> thanks @PiyushNegi1703 for your submission. the self-viva covers `DDL` and `DML` commands well.
> 
> suggestion: consider explaining all the available `DML` and `DML` commands.
> 
> thanks

Hi @th3c0d3br34ker
Here are the videos for the explanation for DDL and DML commands
Part 1 - https://www.loom.com/share/0cb5d74acf97472fb878682b7fdd3fe8?sid=a637d3ba-b8e5-4681-87cb-f4c9261c63ee

Part 2 - https://www.loom.com/share/fae5ed2cc88641b991860a56ceedc511?sid=1fe9d9f1-d7b6-4177-a812-60e4d641733c

**Comment by th3c0d3br34ker** [comment]
thanks @PiyushNegi1703 for reverting, please go ahead and merge this PR.

please re-submit on kalvium.community as well.

**Review by th3c0d3br34ker — APPROVED** [review]

**Pull request merged**
