### PR TITLE
Schema and ER diagram

### PR DESCRIPTION
**Pull request by PiyushNegi1703**
Image of the schema and the er diagram for the database.

### CODE REVIEW

**Comment by Kalvium-Program** [comment]
Add the loom video explaining the diagrams' connections and working.

**Comment by PRASANNAPATHI** [comment]
Add the loom video explaining the diagrams' connections and working.

**Comment by PiyushNegi1703** [comment]
Here is the Loom video for the explanation of schema and erd
https://www.loom.com/share/bf6329b276b14116852069d6dee9dd36?sid=58b7472c-974c-4b77-88fc-19e5af7fc9da

**Comment by PRASANNAPATHI** [comment]
The User , Sport_type and Forum entities should not have postID attribute. Because, the post table only should have all those foreign key connections to all those tables.
And the Posts should not have sportId, as the forumId will indicate the sport,
No proper explanation is given for 'thread', as what it stores.

**Comment by PiyushNegi1703** [comment]
The Posts is an independent entity, it may or may not be present inside a forum that's why it has the sportsId attribute.
I have said in the video that the thread will be used to store the discussions and posts posted in the forum.

Shall I fix the foreign key issue from the diagrams, will I get the marks?

**Comment by PRASANNAPATHI** [comment]
Yeah, now diagram looks fine,
About - thread, I need to know, what is the data type of that? and what It stores?  You explained, it stores discussions and posts, which is not properly understandable, for posts you already have postId,
If you mean it as 'discussion' text data type, then its fine.

**Comment by PRASANNAPATHI** [comment]
You can merge it now.

**Pull request merged**
